import {SmartyPayAPI} from './index';


describe('SmartyPayAPI', ()=>{

  const message = 'test data';
  const secret = 'test key';

  // generated by https://www.devglan.com/online-tools/hmac-sha256-online
  const signature = '4695788ca94015a246422be13bbd966ade571842efc3a39296bdb6f2377597ff';

  test('getMessageSignature', ()=>{

    expect(SmartyPayAPI.getMessageSignature(message, secret)).toBe(signature);

    expect(SmartyPayAPI.getMessageSignature(`NOT-${message}`, secret)).not.toBe(signature);
    expect(SmartyPayAPI.getMessageSignature(message, `NOT-${secret}`)).not.toBe(signature);
  });

  test('isValidSignature', () => {

    expect(SmartyPayAPI.isValidSignature(message, signature, secret)).toBe(true);

    expect(SmartyPayAPI.isValidSignature(`NOT-${message}`, signature, secret)).toBe(false);
    expect(SmartyPayAPI.isValidSignature(message, `NOT-${signature}`, secret)).toBe(false);
    expect(SmartyPayAPI.isValidSignature(message, signature, `NOT-${secret}`)).toBe(false);
  });

});
